[package]
name = "grandlarc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
omp = {path="../../omp"}
rand = "0.8.5"
encoding = "0.2"
encoding-index-simpchinese = "1.20141219.5"
encoding-index-singlebyte = "1.20141219.5"
